const { AIRPORTS_DB } = require('./airportService');

const LOUNGES_DB = {
  JFK:[{name:'Centurion Lounge',terminal:'T4',access:'Amex Platinum / Centurion',hours:'5:30am–11pm',amenities:'Full bar · Hot food · Spa · Wi-Fi · Showers'},{name:'Delta Sky Club',terminal:'T4',access:'Delta Business · Priority Pass Select · Delta Reserve Amex',hours:'5am–10pm',amenities:'Buffet · Bar · Wi-Fi · Quiet zones'},{name:'British Airways Lounge',terminal:'T7',access:'BA Business · Oneworld Sapphire/Emerald',hours:'6am–10pm',amenities:'Food stations · Full bar · Wi-Fi · Concierge'},{name:'No. 1 Lounge',terminal:'T4',access:'Priority Pass · Lounge Key · Pay on arrival ~$50',hours:'5:30am–9pm',amenities:'Buffet · Bar · Wi-Fi · Shower'}],
  LAX:[{name:'Centurion Lounge',terminal:'TBIT',access:'Amex Platinum / Centurion',hours:'5:30am–10pm',amenities:'Full bar · Spa · Hot food · Wi-Fi · Showers'},{name:'Star Alliance Business Lounge',terminal:'TBIT',access:'Star Alliance Business & Gold',hours:'5am–11pm',amenities:'Food buffet · Bar · Wi-Fi · Showers'},{name:'Delta Sky Club',terminal:'T2–T3',access:'Delta Business · Priority Pass Select',hours:'5am–10pm',amenities:'Buffet · Bar · Wi-Fi'},{name:'Korean Air Lounge',terminal:'TBIT',access:'Korean Air Business · SkyTeam Elite Plus',hours:'5am–10pm',amenities:'Korean & Western food · Bar · Wi-Fi'}],
  LHR:[{name:'Concorde Room (BA)',terminal:'T5',access:'BA First Class · Concorde Room card',hours:'5am–9:30pm',amenities:'Fine dining · Champagne bar · Private spa · Butler service'},{name:'Galleries First (BA)',terminal:'T3 & T5',access:'BA First · Oneworld Emerald',hours:'5am–10pm',amenities:'Restaurant · Full bar · Spa · Showers · Private rooms'},{name:'Galleries Club (BA)',terminal:'T3 & T5',access:'BA Business · Oneworld Sapphire · Priority Pass',hours:'5am–10pm',amenities:'Buffet · Bar · Wi-Fi · Showers'},{name:'No. 1 Lounge',terminal:'T2 & T3',access:'Priority Pass · Lounge Key · Pay £35+',hours:'5am–10pm',amenities:'Food · Bar · Wi-Fi · Shower · Spa'}],
  DXB:[{name:'Emirates First Class Lounge',terminal:'T3',access:'Emirates First · Skywards Platinum',hours:'24 hours',amenities:'Fine dining · Premium bar · Spa · Cigar lounge · Private suites · Showers'},{name:'Emirates Business Class Lounge',terminal:'T1 & T3',access:'Emirates Business · Skywards Gold',hours:'24 hours',amenities:'Full buffet · Premium bar · Wi-Fi · Showers'},{name:'Marhaba Lounge',terminal:'T1 & T3',access:'Priority Pass · Lounge Key · Pay AED 180+',hours:'24 hours',amenities:'International buffet · Bar · Wi-Fi · Prayer room · Showers'}],
  DOH:[{name:'Al Mourjan Business Lounge',terminal:'T1',access:'Qatar Business · Privilege Club Platinum/Gold',hours:'24 hours',amenities:'À la carte dining · Full bar · Spa · Wi-Fi · Showers · Prayer room · Kids area'},{name:'Al Safwa First Lounge',terminal:'T1',access:'Qatar First Class only',hours:'24 hours',amenities:'Fine dining · Private rooms · Spa · Butler service · Pool'},{name:'Plaza Premium Lounge',terminal:'T1',access:'Priority Pass · Lounge Key',hours:'24 hours',amenities:'Buffet · Bar · Wi-Fi · Showers'}],
  AUH:[{name:'Etihad First & Business Lounge',terminal:'T3',access:'Etihad First/Business · Etihad Guest Platinum/Gold',hours:'24 hours',amenities:'À la carte dining · Full bar · Spa · Showers · Wi-Fi · Prayer room'},{name:'Premium Lounge by Etihad',terminal:'T1',access:'Priority Pass · Lounge Key',hours:'24 hours',amenities:'Buffet · Bar · Wi-Fi · Showers'}],
  SIN:[{name:'SilverKris First Lounge',terminal:'T3',access:'Singapore Airlines First · PPS Club',hours:'5:30am–12:30am',amenities:'À la carte dining · Champagne bar · Spa · Wi-Fi · Private rooms'},{name:'SilverKris Business Lounge',terminal:'T2 & T3',access:'Singapore Airlines Business · Star Alliance Gold',hours:'5:30am–12:30am',amenities:'Buffet · Bar · Wi-Fi · Showers · Sleeping pods'},{name:'SATS Premier Lounge',terminal:'T1',access:'Priority Pass · Lounge Key · Pay SGD 65+',hours:'24 hours',amenities:'Asian & Western buffet · Bar · Wi-Fi · Shower'}],
  DEL:[{name:'Air India Maharaja Lounge',terminal:'T3',access:'Air India Business · Star Alliance Gold',hours:'24 hours',amenities:'Indian & international cuisine · Bar · Wi-Fi · Showers'},{name:'Encalm Lounge',terminal:'T3',access:'Priority Pass · Lounge Key · Pay INR 3500+',hours:'24 hours',amenities:'Full buffet · Bar · Wi-Fi · Showers · Spa'},{name:'Plaza Premium Lounge',terminal:'T3',access:'Priority Pass · Visa Infinite',hours:'24 hours',amenities:'Buffet · Bar · Wi-Fi · Shower'}],
  BOM:[{name:'GVK Mumbai T2 Lounge',terminal:'T2',access:'Priority Pass · Lounge Key · Visa Infinite',hours:'24 hours',amenities:'Indian & international buffet · Bar · Wi-Fi · Shower'},{name:'Taj Lounge',terminal:'T2',access:'Eligible airline business/first class',hours:'24 hours',amenities:'Premium dining · Bar · Wi-Fi'}],
  CDG:[{name:'Air France La Première Lounge',terminal:'2E/2F',access:'AF First Class · Flying Blue Platinum',hours:'5:30am–10pm',amenities:'Chef dining · Wine cellar · Spa · Concierge · Showers'},{name:'Air France Business Lounge',terminal:'2E/2F/2G',access:'AF Business · Flying Blue Gold · SkyTeam Elite+',hours:'5am–11pm',amenities:'Buffet · Full bar · Wi-Fi · Showers'},{name:'No. 1 Lounge',terminal:'2E',access:'Priority Pass · Pay €35+',hours:'6am–9:30pm',amenities:'Buffet · Bar · Wi-Fi · Shower'}],
  FRA:[{name:'Lufthansa Senator Lounge',terminal:'T1 & T2',access:'LH Business · Miles & More Senator · Star Alliance Gold',hours:'5am–10pm',amenities:'À la carte dining · Full bar · Wi-Fi · Showers · Cigar room'},{name:'Lufthansa Business Lounge',terminal:'T1 & T2',access:'LH Business · Star Alliance Silver · Priority Pass',hours:'5am–10pm',amenities:'Hot & cold buffet · Full bar · Wi-Fi'},{name:'Lufthansa First Class Terminal',terminal:'Separate FCS building',access:'LH First · HON Circle members only',hours:'5am–10pm',amenities:'Private terminal · Chauffeur · Fine dining · Concierge · Nap rooms'}],
  IST:[{name:'Turkish Airlines Business Lounge',terminal:'T1',access:'TK Business · Miles & Smiles Elite Plus · Star Alliance Gold',hours:'24 hours',amenities:'Gourmet buffet · Premium bar · Spa · Wi-Fi · Showers · Cinema · Golf simulator'},{name:'CIP Lounge',terminal:'T1',access:'Priority Pass · Lounge Key · Pay on arrival',hours:'24 hours',amenities:'Buffet · Bar · Wi-Fi · Showers'}],
  HKG:[{name:'The Pier Business Lounge (CX)',terminal:'T1',access:'Cathay Business · Oneworld Sapphire',hours:'5:30am–1am',amenities:'Noodle bar · Full bar · Wi-Fi · Showers · Nap rooms'},{name:'The Wing First Lounge (CX)',terminal:'T1',access:'Cathay First · Oneworld Emerald',hours:'5:30am–1am',amenities:'Fine dining · Wine cellar · Spa · Private cabanas'},{name:'Plaza Premium Lounge',terminal:'T1',access:'Priority Pass · Lounge Key · Pay on arrival',hours:'24 hours',amenities:'Dim sum buffet · Bar · Wi-Fi · Shower'}],
  NRT:[{name:'JAL Sakura Lounge',terminal:'T2',access:'JAL Business · Oneworld Sapphire',hours:'6am–8pm',amenities:'Japanese & Western dining · Bar · Wi-Fi · Showers'},{name:'ANA Suite Lounge',terminal:'T1',access:'ANA Business · Star Alliance Gold',hours:'5:30am–8pm',amenities:'Premium dining · Bar · Wi-Fi · Showers · Spa'},{name:'IASS Superior Lounge',terminal:'T1 & T2',access:'Priority Pass · Lounge Key',hours:'6am–8pm',amenities:'Buffet · Bar · Wi-Fi'}],
  ICN:[{name:'Korean Air Prestige Lounge',terminal:'T1 & T2',access:'Korean Air Business · SkyTeam Elite Plus',hours:'24 hours',amenities:'Korean & international dining · Full bar · Spa · Wi-Fi · Sleeping rooms'},{name:'Asiana Business Lounge',terminal:'T1',access:'Asiana Business · Star Alliance Gold',hours:'5am–11pm',amenities:'Korean cuisine · Bar · Wi-Fi · Showers'},{name:'SkyHub Lounge',terminal:'T2',access:'Priority Pass · Lounge Key',hours:'6am–9pm',amenities:'Buffet · Bar · Wi-Fi'}],
  ATL:[{name:'Delta Sky Club',terminal:'Concourse A/B/C/D/E/F',access:'Delta Business · Priority Pass Select · Delta Reserve Amex',hours:'5am–10pm',amenities:'Full buffet · Bar · Wi-Fi · Showers (select)'},{name:'Escape Lounge',terminal:'Concourse B',access:'Priority Pass · Lounge Key',hours:'5am–9pm',amenities:'Snacks · Bar · Wi-Fi'}],
  ORD:[{name:'Centurion Lounge',terminal:'T3',access:'Amex Platinum / Centurion',hours:'5am–9pm',amenities:'Full bar · Hot food · Spa · Wi-Fi · Showers'},{name:'United Club',terminal:'T1 & T2',access:'United Business · Star Alliance Gold · United Club card',hours:'5am–10pm',amenities:'Buffet · Full bar · Wi-Fi'},{name:'Delta Sky Club',terminal:'T5',access:'Delta Business · Priority Pass Select',hours:'5am–9pm',amenities:'Buffet · Bar · Wi-Fi'}],
  SYD:[{name:'Qantas First Lounge',terminal:'T1',access:'Qantas First · Oneworld Emerald',hours:'Varies by flight',amenities:'Neil Perry restaurant · Wine cellar · Spa · Showers'},{name:'Qantas Business Lounge',terminal:'T1 & T3',access:'Qantas Business · Oneworld Sapphire',hours:'5:30am–10pm',amenities:'Buffet · Bar · Wi-Fi · Showers'},{name:'Plaza Premium Lounge',terminal:'T1',access:'Priority Pass · Lounge Key',hours:'Varies',amenities:'Buffet · Bar · Wi-Fi · Shower'}],
  EWR:[{name:'United Club',terminal:'B',access:'United Business · Star Alliance Gold · United Club card',hours:'4:30am–9pm',amenities:'Hot food · Full bar · Wi-Fi · Showers'},{name:'No. 1 Lounge',terminal:'B',access:'Priority Pass · Lounge Key · Pay on arrival ~$45',hours:'5am–9pm',amenities:'Buffet · Bar · Wi-Fi · Comfortable seating'}],
  MIA:[{name:'Centurion Lounge',terminal:'D',access:'Amex Platinum / Centurion',hours:'5:30am–10pm',amenities:'Full bar · Hot food · Spa · Wi-Fi · Showers'},{name:'American Airlines Admirals Club',terminal:'D',access:'AA Business · Oneworld Sapphire · Admirals Club card',hours:'5am–10pm',amenities:'Buffet · Bar · Wi-Fi · Showers'},{name:'LATAM Lounge',terminal:'E',access:'LATAM Business · oneworld Sapphire',hours:'5am–10pm',amenities:'South American cuisine · Bar · Wi-Fi'}],
  DEN:[{name:'United Club',terminal:'B/C',access:'United Business · Star Alliance Gold · United Club card',hours:'4:30am–9pm',amenities:'Hot food · Full bar · Wi-Fi'},{name:'Centurion Lounge',terminal:'C',access:'Amex Platinum / Centurion',hours:'5am–9pm',amenities:'Full bar · Hot food · Spa · Wi-Fi · Showers'},{name:'The Club at DEN',terminal:'C',access:'Priority Pass · Lounge Key · Pay ~$45',hours:'5am–9pm',amenities:'Buffet · Bar · Wi-Fi'}]
};

const TRANSPORT_DB = {
  JFK:{taxi:'$52–80 flat rate to Manhattan',uber:'$45–75 (surge may apply)',transit:'AirTrain + Subway (E/J/Z): $9.25 · 50–75 min',bus:'NYC Express Bus: $19 · 50–80 min',shuttle:'Shared: $20–28 per person',parking:'$38–45/day on-airport'},
  LAX:{taxi:'$50–75 to downtown Los Angeles',uber:'$35–60',transit:'FlyAway Bus to Union Station: $9.75 · 40–50 min; Metro C Line transfer available',bus:'Big Blue Bus / METRO: $1.75–2.50 · 60–90 min',shuttle:'Shared: $18–25 per person',parking:'$40–55/day'},
  LHR:{taxi:'£50–70 to central London (metered)',uber:'£45–65',transit:'Elizabeth Line (Crossrail): £12.70 · 23–32 min to Paddington',bus:'National Express: £6–10 · 60–90 min',shuttle:'Hotel shuttle: £15–25',parking:'From £29/day'},
  DXB:{taxi:'AED 70–100 to downtown / DIFC (metered)',uber:'AED 60–90',transit:'Dubai Metro Red Line: AED 12–14 · 35–50 min to Union Station',bus:'RTA Bus: AED 4–6 · 60–90 min',shuttle:'Many hotels offer free shuttle; others AED 40–70',parking:'AED 10–40/day'},
  DOH:{taxi:'QAR 35–60 to West Bay / downtown Doha',uber:'QAR 30–55',transit:'Doha Metro (Hamad Intl → Al Matar): QAR 2–4 · 20 min',bus:'Qatar Bus: QAR 4–8 · 45–70 min',shuttle:'Hotel shuttle: free–QAR 30',parking:'QAR 20–50/day'},
  AUH:{taxi:'AED 60–90 to Abu Dhabi city centre',uber:'AED 50–80',transit:'No direct metro yet; city bus service available',bus:'Aldar Bus E101: AED 4 · 40–50 min to city',shuttle:'Hotel shuttle: free–AED 40',parking:'AED 15–35/day'},
  SIN:{taxi:'SGD 20–35 to Orchard Rd / Marina Bay',uber:'SGD 18–30',transit:'MRT (East-West Line): SGD 2.10–2.90 · 35–45 min to City Hall',bus:'Public bus 36: SGD 1.50 · 60–90 min',shuttle:'CityShuffle: SGD 9',parking:'SGD 12–32/day'},
  DEL:{taxi:'INR 600–900 to Connaught Place (pre-paid taxi)',uber:'INR 400–700',transit:'Delhi Metro (Magenta/Orange Line): INR 60–100 · 40–55 min to Central Secretariat',bus:'AC Bus service: INR 75–125 · 60–90 min',shuttle:'Hotel shuttle: free–INR 500',parking:'INR 200–600/day'},
  BOM:{taxi:'INR 500–800 to south Mumbai (metered)',uber:'INR 350–600',transit:'No direct rail link yet to T2; city bus from T1',bus:'BEST Bus: INR 20–40 · 60–120 min',shuttle:'Hotel shuttle: free–INR 400',parking:'INR 150–400/day'},
  CDG:{taxi:'€55–65 flat rate to Paris Centre (Left/Right Bank by law)',uber:'€45–60',transit:'RER B: €12.10 · 35–45 min to Gare du Nord / Châtelet',bus:'Le Bus Direct: €17–19 · 50–70 min to Arc de Triomphe/Montparnasse',shuttle:'Shared: €20–30',parking:'From €25/day'},
  FRA:{taxi:'€35–55 to Frankfurt city centre (metered)',uber:'€30–50',transit:'S-Bahn S8/S9: €5.10 · 12 min to Frankfurt Hauptbahnhof',bus:'Lufthansa Express Bus: €12–16 to city',shuttle:'Hotel shuttle: varies',parking:'From €18/day'},
  IST:{taxi:'TRY 250–400 / ~€8–12 to Taksim (European side)',uber:'TRY 200–350',transit:'Metro M11: TRY 45 · 40 min to Gayrettepe',bus:'Havabus: TRY 90–120 · 60–90 min',shuttle:'Airport transfer: €15–30',parking:'From TRY 250/day'},
  ORD:{taxi:'$35–55 to Chicago Magnificent Mile',uber:'$28–50',transit:'Blue Line CTA: $5 · 45 min to Clark/Lake',bus:'Express bus: $9 · 35–50 min',shuttle:'Shared: $25–35',parking:'$34–40/day'},
  ATL:{taxi:'$30–45 to downtown Atlanta',uber:'$25–40',transit:'MARTA Rail (Red/Gold Line): $2.50 · 20 min to Five Points',bus:'MARTA Bus: $2.50 · 25–40 min',shuttle:'Shared: $15–25',parking:'$30–38/day'},
  DFW:{taxi:'$35–50 to downtown Dallas',uber:'$30–45',transit:'DART Rail (Orange Line): $2.50 · 45 min to Victory Station',bus:'TRE: varies',shuttle:'Shared: $20–28',parking:'$24–35/day'},
  NRT:{taxi:'JPY 20,000–25,000 to central Tokyo (metered)',uber:'JPY 18,000–23,000',transit:'Narita Express (N\'EX): JPY 3,020 · 60 min to Shinjuku',bus:'Limousine Bus: JPY 3,200 · 80–90 min',shuttle:'Hotel shuttle: varies',parking:'JPY 500–2,000/day'},
  HND:{taxi:'JPY 8,000–12,000 to central Tokyo',uber:'JPY 7,000–11,000',transit:'Tokyo Monorail: JPY 500 · 18 min to Hamamatsucho',bus:'Keikyu Bus: JPY 600–1,200 · 20–40 min',shuttle:'Hotel shuttle: varies',parking:'JPY 800–2,500/day'},
  ICN:{taxi:'KRW 60,000–90,000 to central Seoul',uber:'KRW 55,000–85,000',transit:'AREX Express: KRW 9,500 · 43 min to Seoul Station',bus:'Airport Bus (Limousine): KRW 15,000 · 60–90 min',shuttle:'Hotel shuttle: varies',parking:'From KRW 24,000/day'},
  HKG:{taxi:'HKD 350–420 to Kowloon (metered)',uber:'HKD 300–380',transit:'Airport Express: HKD 100 · 24 min to Hong Kong Station',bus:'Cityflyer bus: HKD 33–50 · 45–75 min',shuttle:'Hotel shuttle: varies',parking:'From HKD 200/day'},
  SYD:{taxi:'AUD 50–70 to Sydney CBD',uber:'AUD 45–65',transit:'Airport Link Train: AUD 19.38 · 12 min to Central (note: expensive surcharge)',bus:'350 express bus: AUD 5.50 · 45 min (much cheaper)',shuttle:'Shared: AUD 20–30',parking:'From AUD 25/day'},
  EWR:{taxi:'$50–75 to Midtown Manhattan (metered)',uber:'$45–70',transit:'AirTrain + NJ Transit to Newark Penn: $17 total · 30–45 min to NYC Penn Station',bus:'Coach USA to Port Authority NYC: $17–19 · 45–60 min',shuttle:'Shared: $20–28 per person',parking:'$27–35/day on-airport'},
  MIA:{taxi:'$25–40 to downtown Miami (metered)',uber:'$20–35',transit:'MIA Mover (free) + Miami-Dade Metrorail: $2.25 · 25–35 min to Brickell',bus:'Miami-Dade Bus: $2.25 · 45–60 min',shuttle:'Shared: $15–22 per person',parking:'$20–30/day'},
  DEN:{taxi:'$45–60 to downtown Denver (metered)',uber:'$35–55',transit:'University of Colorado A Line: $10.50 · 37 min to Union Station',bus:'RTD Bus: $3 · 55–75 min',shuttle:'Shared: $18–25 per person',parking:'$26–36/day'},
  DEFAULT:{taxi:'Pre-book through hotel or use official metered taxi at arrivals',uber:'Check Uber/Bolt/Careem app for local ride-share availability',transit:'Check the airport\'s official website for public transport options',bus:'Airport coach/shuttle services often connect to city centre',shuttle:'Many hotels offer complimentary airport pickup — call ahead',parking:'Book parking in advance for best rates'}
};

function getAirportInfo(iata) {
  const lounges = LOUNGES_DB[iata] || [];
  const transport = TRANSPORT_DB[iata] || TRANSPORT_DB.DEFAULT;
  const airport = AIRPORTS_DB.find(a => a.iata === iata) || {};
  return { iata, name: airport.name || '', city: airport.city || '', country: airport.country || '', lounges, transport };
}

module.exports = { LOUNGES_DB, TRANSPORT_DB, getAirportInfo };
